- name: Deploy
  hosts: all
  remote_user: pi
  become: true
  vars:
    DD_API_KEY: "{{ lookup('ansible.builtin.env', 'DD_API_KEY') }}"
    DD_APP_KEY: "{{ lookup('ansible.builtin.env', 'DD_APP_KEY') }}"
  tasks:
  - name: Copy systemd unit file
    ansible.builtin.template:
      src: ./pi-brew.service
      dest: /etc/systemd/system/pi-brew.service
      owner: root
      group: root
  - name: Copy datadog api key
    ansible.builtin.template:
      src: ./.dd-api-key.tmpl
      dest: /home/pi/.dd-api-key
      owner: root
      group: root
  - name: Copy datadog app key
    ansible.builtin.template:
      src: ./.dd-app-key.tmpl
      dest: /home/pi/.dd-app-key
      owner: root
      group: root
  - name: Copy pi-brew binary
    ansible.builtin.copy:
      src: ../bin/pi-brew
      dest: /home/pi/pi-brew
      mode: '0755'
      owner: pi
      group: pi
      force: yes
  - name: Restart pi-brew systemd unit
    systemd:
      daemon_reload: yes
      enabled: yes
      force: yes
      name: pi-brew
      state: restarted
  - name: Copy log-forwader binary
    ansible.builtin.copy:
      src: ../bin/log-forwarder
      dest: /home/pi/log-forwarder
      mode: '0755'
      owner: root
      group: root
      force: yes
    register: forwarder_binary
  - name: Copy forwarder systemd unit file
    ansible.builtin.template:
      src: ../log-forwarder/systemd-unit.service.j2
      dest: /etc/systemd/system/log-forwarder.service
      owner: root
      group: root
    register: forwarder_systemd
  - name: Restart forwarder systemd unit
    become: true
    systemd:
      daemon_reload: yes
      enabled: yes
      force: yes
      name: log-forwarder
      state: restarted
    when: forwarder_binary.changed | bool or forwarder_systemd.changed | bool